### PR TITLE
Adding handling :eof value

### PR DESCRIPTION
**Pull request by metelik**
Handling right hand mismatch in the case of U-boot environment variables' device hasn't been configured aka :eof value.

### CODE REVIEW

**Comment by ConnorRigby** [comment]
I think this is a valid use case, but this adds more nesting to an already nested function. Would you mind splitting parts into separate private functions maybe?

**Comment by metelik** [comment]
I was thinking about it @ConnorRigby did not want to make too many changes at once. I shall submit the re-work soon - first I must not get late to my karate practice.

**Comment by metelik** [comment]
O.k. Re-work done ;)

**Comment by fhunleth** [comment]
I just noticed this. It looks like this change is good except that it could use a unit test. @ConnorRigby?

**Comment by fhunleth** [comment]
Merged. Thanks!

**Pull request closed without merging**
